/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "mainappapi",
            "endpoint": "https://bedyr43119.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:b63e2a2e-4454-4a61-83cb-c40afed0b759",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_2EkIJUvSL",
    "aws_user_pools_web_client_id": "1pspkku32mcoavd5q3m4tdv66k",
    "oauth": {}
};


export default awsmobile;
